fix = true
src = ["src"]

[lint]
select = [
    "ASYNC",
    "B",
    "D",
    "E",
    "F",
    "I",
    "PIE",
    "PL",
    "RUF100",
    "S",
    "SIM",
    "UP",
    "W",
]
ignore = [
    "D100",
    "D103",
    "D107",
]

pydocstyle.convention = "google"
