leaguewizard::api::callback_handler
leaguewizard::api::callback_handler.champion_tracker
Any leaguewizard.api.callback_handler._get_latest_version(aiohttp.ClientSession client, str url="https://ddragon.leagueoflegends.com/api/versions.json")
Retrieves the latest DDragon version from the Riot Games API. Args: client (aiohttp.ClientSession): The aiohttp client session. url (str): The URL to fetch the versions from. Defaults to "https://ddragon.leagueoflegends.com/api/versions.json". Returns: Any: The latest version string.
Referenced by leaguewizard.api.callback_handler._get_champion_dict.
Any leaguewizard.api.callback_handler._get_champion_dict(aiohttp.ClientSession client)
Retrieves a dictionary mapping champion IDs to champion names. Args: client (aiohttp.ClientSession): The aiohttp client session. Returns: Any: A dictionary of champion IDs (int) mapped to their champion names (str).
References leaguewizard.api.callback_handler._get_latest_version.
Referenced by leaguewizard.api.callback_handler.get_champion_name, leaguewizard.api.callback_handler.on_message.
None leaguewizard.api.callback_handler.send_itemsets(aiohttp.ClientSession client, PayloadItemSets payload, int account_id, SSLContext context)
Sends item set data for a given account ID. Args: client: An aiohttp client session for making HTTP requests. payload: The PayloadItemSets object containing the item set data. account_id: The unique identifier for the League of Legends account. context: An SSLContext object for secure HTTP connections.
Referenced by leaguewizard.api.callback_handler.on_message.
None leaguewizard.api.callback_handler.send_perks(aiohttp.ClientSession client, PayloadPerks payload, SSLContext context)
Deletes the current rune page and creates a new one. Deletes the current rune page if it exists and then creates a new rune page based on the provided payload. Args: client: An aiohttp.ClientSession for making HTTP requests. payload: A PayloadPerks object containing the data for the new rune page. context: An SSLContext for establishing secure connections.
Referenced by leaguewizard.api.callback_handler.on_message.
None leaguewizard.api.callback_handler.send_spells(aiohttp.ClientSession client, PayloadSpells payload, SSLContext context)
Sends a spell to the League of Legends client. Args: client: An aiohttp client session. payload: The payload containing spell information. context: The SSL context for the client.
Referenced by leaguewizard.api.callback_handler.on_message.
str | None leaguewizard.api.callback_handler.get_champion_name(aiohttp.ClientSession client, int champion_id)
Retrieves the name of a champion given their ID. Args: client (aiohttp.ClientSession): The aiohttp client session. champion_id (int): The ID of the champion. Returns: str | None: The champion's name if found, otherwise None.
References leaguewizard.api.callback_handler._get_champion_dict.
None leaguewizard.api.callback_handler.on_message(str|bytes event, aiohttp.ClientSession conn, int aio_client_id)
Handles incoming messages from a connection. Args: event: The incoming message event. conn: The aiohttp client session for the connection. aio_client_id: Random int to ensure there is only one aiohttp ClientSession being used.
References leaguewizard.api.callback_handler._get_champion_dict, leaguewizard.api.callback_handler.handle_auto_accept, leaguewizard.api.callback_handler.send_itemsets, leaguewizard.api.callback_handler.send_perks, leaguewizard.api.callback_handler.send_spells.
None leaguewizard.api.callback_handler.handle_auto_accept(Any conn)
Handles the automatic acceptance of game phases.
Referenced by leaguewizard.api.callback_handler.on_message.